### ISSUE TITLE
patch diff format

### ISSUE THREAD

**Issue by cech12** [DigglesMods/DigglesModManager#18]
Change the Mod format to the patch diff format (like git)

Carsten Orthbandt: "Wäre es nicht sicherer, das "normale" PatchDiff-Format zu benutzen? Die Suchen-Ersetzen-Methode ist u.U. zu unscharf, um Änderungen korrekt abzubilden. Sie benutzen ja schon Github und damit wohl auch git selbst. Das Format, dass "git diff" ausspuckt ist das reguläre patch-diff-Format."

**Comment by iGilga** [comment]
Hello. Seriously, what is this ex-teamleader?

**Comment by iGilga** [comment]
@cech12 , Sorry. I found this person Carsten Orthbandt on resume.
`1998 - 2006 Founder and Development Director at SEK Berlin,
Technology Lead for "Wiggles" (Innonics) and "ParaWorld" (Ubisoft)`
Ok. But i cant understand what need pathDiff current game Wiggles.
Or develop a new tool for follow up on change files?

**Comment by cech12** [comment]
Yes, Carsten Orthbandt is one of the developers of Wiggles. And he gave the tip to use the patch diff format for the DigglesModManager. Nothing more. ;)

**Comment by iGilga** [comment]
Apply algorithm for files, did I understand correctly?

**Comment by iGilga** [comment]
ok.
For develops\modding diffpatch good.

**Comment by cech12** [comment]
The patch diff format is not used by users, because they only click buttons in the DigglesModManager. It would be a better (and sharper) solution for the mods and maybe faster for the "Let's Mod"-funktionality of the DigglesModManager. So for the mod developers it could be an enhancement.

If it should be implemented the old method ($start...) has to transformed to the patch diff format. (in mods and DigglesModManager) 

This repository has nothing to do with the game wiggles itself!

**Comment by cech12** [comment]
I think this enhancement will never be implemented. So, I close this issue.
