### ISSUE TITLE
start the campaign as diffrent clan

### ISSUE THREAD

**Issue by P1tt187** [DigglesMods/DigglesModManager#22]
Idee für eine weitere mod:

Wir alle wollten doch schon immer einmal die Kampange mit einem anderen Volk durchspielen.
Ich habe nach einigen recherchen herausgefunden, dass man hierfür lediglich 
`Wiggles/Data /Scripts/gameplay/CampaignInit.tcl`
bearbeiten muss.
Darin gibt es den folgenden Block:
`set_ownerrace 	0 0`
`set_ownerrace	1 1 `
`set_ownerrace	2 2 `
`set_ownerrace	3 3`
`set_ownerrace	4 4`
Ändert man die ersten beiden zu
`set_ownerrace 	0 1`
`set_ownerrace	1 0 `
Startet man als Vodoo und die Vodoos werden zu Wiggles
[Quelle](https://translate.google.com/translate?hl=en&sl=auto&tl=de&u=http%3A%2F%2Fwiggles.sux.cz%2Ftema%2F10920-scripty-aneb-menime-svet)

Idea for a new mod:
We all ever wantet to play the campaign with a diffrent clan. Through researches I found out, that the file `Wiggles/Data /Scripts/gameplay/CampaignInit.tcl` have to be modificated to achive this.
In this file is a textblock:
`set_ownerrace 	0 0`
`set_ownerrace	1 1 `
`set_ownerrace	2 2 `
`set_ownerrace	3 3`
`set_ownerrace	4 4`
if the first two lines are moificatet to this
`set_ownerrace 	0 1`
`set_ownerrace	1 0 `
The diggles becomes vodoo and the vodoo becomes diggles
[source](http://wiggles.sux.cz/tema/10920-scripty-aneb-menime-svet)

**Comment by cech12** [comment]
Hey! 
Cooler Vorschlag! Wir haben diese Idee schon in unserer [Ideen-Liste](https://github.com/DigglesMods/DigglesModManager/wiki/Ideen#wiggle-skin-%C3%84nderung), weil Simon das [früher schon einmal als Mod](http://web.archive.org/web/20090519045732/http://wiggles.foren-city.de/topic,95,-mod-clan-mod.html) angeboten hatte. 
Die Umsetzung war aber anders und auch etwas komplizierter als das, was du hier vorschlägst. :)
Daher sehr coole und einfache Art, das umzusetzen. Ich werde den Link der Ideen-Liste hinzufügen, mir das mal ansehen und mich melden. 👍

**Comment by cech12** [comment]
Hey! 
Ich habe mir das mal angesehen und das funktioniert auf den ersten Blick ziemlich gut! Daher habe ich mal eine erste Version der Mod erstellt: https://github.com/DigglesMods/ChangeCampaignClan/releases

Es ist noch kaum getestet. Man müsste am besten mit jedem Clan einmal die komplette Kampagne durchspielen, um sicher zu gehen, dass alles funktioniert. 

Leider habe ich nicht so viel Zeit, das allein zu schaffen. Daher wäre es cool, wenn du das vielleicht auch mal testest. ;)

**Comment by cech12** [comment]
Gab es irgendwelche Grafik-Bugs oder ähnliches Auffälliges?

**Comment by P1tt187** [comment]
bei mir nicht ;)

**Comment by cech12** [comment]
Ich frage, weil es wohl damals Grafikbugs bei der Lorelei gab.

**Comment by P1tt187** [comment]
die grafikbugs die ich beobachtet hatte sind nur unter windows aufgetreten und hingen mit den eingeschalteten effekten zusammen, daher schreibe ich sie nicht der mod zu
unter linux mit wine sah alles normal aus

**Comment by P1tt187** [comment]
mit welchem volk hast du es versucht?

**Comment by cech12** [comment]
Ich habe es nur mit allen Clans mal angespielt. Aber ich war nur in der Oberwelt.

**Comment by cech12** [comment]
Version v0.1 der neuen [ChangeCampaignClan-Mod](https://github.com/DigglesMods/ChangeCampaignClan/releases) ist nun im DigglesModManager enthalten. Falls dort Probleme auftreten sollten, wird im Repository der Mod ein neuer Issue erstellt.
Somit kann diese Mod-Anfrage geschlossen werden.
