### ISSUE TITLE
Forum Tod?

### ISSUE THREAD

**Issue by Andrax1977** [DigglesMods/DigglesModManager#28]
Tach,

ich wähle mal diesen Weg.
Ich versuche mich sei einiger Zeit im Wiggle-Forum (wiggles.ruka.at/forum/) anzumelden.
Man bekommt aber keine Bestätigungsmail und der Admin meldet sich auch nicht.
Ist das Forum Tod?

**Comment by cech12** [comment]
Probleme mit dem Forum haben hier nichts verloren. Ich kann versuchen, das Problem weiterzugeben. 
Wenn du Probleme mit Wiggles hast und dich nicht im Forum anmelden kannst, dann empfehle ich dir den Discord-Server: https://discord.gg/JUtVc69

Da bin ich auch häufig online und auch andere, die dir vielleicht bei deinen Problemen helfen können
