### ISSUE TITLE
Trigger open dev console via mod

### ISSUE THREAD

**Issue by P1tt187** [DigglesMods/DigglesModManager#31]
I'm using the gog version of the game. Currently the `-console` Parameter doesn't work. Is it Possible to trigger the event to open the console using a mod?

**Comment by cech12** [comment]
Until now, I have not found a possibility to do this.

**Comment by iGilga** [comment]
> I'm using the gog version of the game. Currently the `-console` Parameter doesn't work. Is it Possible to trigger the event to open the console using a mod?

You mean how show console in game? if yes, just check shift or ctrl + PrintScreen/Pause/Scroll. For notebook or laptop Shift/Ctrl + Fn + home/del/end.

**Comment by cech12** [comment]
@iGilga Please see the link :)

**Comment by cech12** [comment]
GOG released a new version 2.1.1.8 where the problem is fixed.
