### ISSUE TITLE
Nude Patch

### ISSUE THREAD

**Issue by cech12** [DigglesMods/DigglesModManager#33]
Back in days there was a nude pqtch that made the fairy naked. This feature could be added by a mod.

**Comment by cech12** [comment]
Added a new mod: https://github.com/DigglesMods/ElfPatch

**Comment by Aehrraid** [comment]
Is this resolved now?

**Comment by cech12** [comment]
should be added to release script :) then it is resolved

**Comment by cech12** [comment]
added
