### ISSUE TITLE
Migrate continuous builds to GitHub Actions

### ISSUE THREAD

**Issue by Aehrraid** [DigglesMods/DigglesModManager#37]
Build-On-Commit is on travis right now. There is some migration going on there which might break the configuration. State of the art is GitHub Actions right now.

**Comment by Aehrraid** [comment]
Sadly, the project still runs on .NET 4.X, this makes it a bit more non-trivial. We might actually migrate to .NET 5.0 (which is brand new) aswell. There is no real gain, though...

**Comment by cech12** [comment]
This project runs on .NET 4.0 to support Windows XP. So, I am against an update to a actual version of .NET

https://github.com/DigglesMods/DigglesModManager/commit/024a9fb56f50f5a7957860f81aca8f646ba32083

**Comment by Aehrraid** [comment]
Solved with #39
