### ISSUE TITLE
ModManager is blurry when scaled/zoomed on Windows 10

### ISSUE THREAD

**Issue by Aehrraid** [DigglesMods/DigglesModManager#40]
On Windows 10 using the "Change the size of text, apps and other items" other than the recommended, the ModManager gets blurry. We might want to try to fix that.

I found http://crsouza.com/2015/04/13/how-to-fix-blurry-windows-forms-windows-in-high-dpi-settings/ and some other tips regarding this problem.

I am not sure, whether this is fixable on the current .NET-Version while also being able to support Windows XP.

I attached a screenshot of my application while being blurred (zoom 125%) and not blurred (zoom 100%) on a 2560x1440 monitor.

![image](https://user-images.githubusercontent.com/6419798/103233960-b77aa400-493e-11eb-9c2b-6eaff36f9066.png)
![image](https://user-images.githubusercontent.com/6419798/103233984-cbbea100-493e-11eb-8588-28c30b7258a1.png)

**Comment by cech12** [comment]
It would be pretty cool if that would be supported. But when I look at some windows in Visual Studio, I have the same problems. If even Microsoft can't do that everywhere, I think we'd better invest our time in other things. :D

**Comment by cech12** [comment]
Was not fixed with this PR

**Comment by cech12** [comment]
Unfortunately, support for Windows XP can no longer be maintained. Therefore, an update to .NET 6 is pending, which will also fix this issue. :)
